#baseURL = "http://www.loongarch.dev/"
baseURL = "/"
title = "LoongArch 开放社区"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2016-{year} Community Team. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

# Pagination
paginate = 8
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# vim: ft=conf ts=2 sw=2 et
